version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - TG_BOT_WORKERS=4
      - OWNER_ID=${OWNER_ID}
